name: Iterate JSON and Hit API

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Verify JSON file exists
      - name: Verify JSON file
        run: ls -la ./data.json

      # Step 3: Iterate JSON and Call API
      - name: Process JSON and Hit API
       run: |
          cat ./data.json | jq -c '.[]' | while read -r item; do
            echo "Processing item: $item"
            # curl -X POST \
            #   -H "Content-Type: application/json" \
            #   -H "tenant-id: ${{ secrets.TENANT_ID }}" \
            #   -H "api-key: ${{ secrets.API_KEY }}" \
            #   -d "$item" \
            #   https://api.example.com/endpoint
          done