name: Iterate JSON and Hit API

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Verify JSON file exists
      - name: Verify JSON file
        run: ls -la ./data.json

      # Step 3: Iterate JSON and Call API
      - name: Process JSON and Hit API
        run: |
          python3 -c "
import json
import requests

# Load JSON data from file
with open('./data.json', 'r') as file:
    data = json.load(file)

# API headers
headers = {
    'Content-Type': 'application/json',
    'tenant-id': '${{ secrets.TENANT_ID }}',
    'api-key': '${{ secrets.API_KEY }}'
}

# Process each object in the JSON file
for item in data:
    print(f'Processing item: {item}')
    try:
        response = requests.post('https://api.example.com/endpoint', json=item, headers=headers)
        print(f'Status: {response.status_code}, Response: {response.text}')
    except Exception as e:
        print(f'Error processing item {item}: {e}')
          "
